import * as z from "zod";

const YOUTUBE_VIDEO_ID_PATTERN = /^[A-Za-z0-9_-]{11}$/;

export const AVA_FIRST_WORD_VIDEO_SLUGS = [
  "mommy",
  "daddy",
  "baby",
  "grandma",
  "grandpa",
  "brother",
  "sister",
  "friend",
  "boy",
  "girl",
  "dog",
  "cat",
  "bird",
  "fish",
  "cow",
  "horse",
  "duck",
  "bunny",
  "bear",
  "frog",
  "apple",
  "banana",
  "milk",
  "water",
  "bread",
  "cheese",
  "egg",
  "cookie",
  "juice",
  "peas",
  "eyes",
  "nose",
  "mouth",
  "ears",
  "hands",
  "feet",
  "hair",
  "teeth",
  "belly",
  "face",
  "bed",
  "chair",
  "table",
  "door",
  "window",
  "light",
  "bath",
  "book",
  "blanket",
  "phone",
  "ball",
  "blocks",
  "doll",
  "teddy-bear",
  "car",
  "train",
  "bubbles",
  "puzzle",
  "crayon",
  "drum",
  "sun",
  "moon",
  "star",
  "tree",
  "flower",
  "grass",
  "rain",
  "cloud",
  "rock",
  "leaf",
  "bus",
  "truck",
  "bicycle",
  "airplane",
  "boat",
  "stroller",
  "wagon",
  "tractor",
  "helicopter",
  "scooter",
  "eat",
  "drink",
  "sleep",
  "sit",
  "stand",
  "walk",
  "run",
  "jump",
  "clap",
  "hug",
  "more",
  "all-done",
  "yes",
  "no",
  "please",
  "thank-you",
  "help",
  "up",
  "down",
  "go",
] as const;

export const AvaFirstWordSlugSchema = z.enum(AVA_FIRST_WORD_VIDEO_SLUGS);
export type AvaFirstWordSlug = z.infer<typeof AvaFirstWordSlugSchema>;

export const AvaFirstWordVideoClipSchema = z.object({
  youtubeVideoId: z.string().regex(YOUTUBE_VIDEO_ID_PATTERN),
  startSeconds: z.int().min(0),
  durationSeconds: z.literal(5),
  sourceTitle: z.string().min(1),
  sourceChannel: z.string().min(1),
  note: z.string().min(1).optional(),
});
export type AvaFirstWordVideoClip = z.infer<typeof AvaFirstWordVideoClipSchema>;

export const AvaFirstWordVideoManifestSchema = z.record(
  AvaFirstWordSlugSchema,
  AvaFirstWordVideoClipSchema,
);
export type AvaFirstWordVideoManifest = z.infer<typeof AvaFirstWordVideoManifestSchema>;

const VIDEO_SOURCE_KEYS = [
  "abcFirstWords",
  "brightyVehicles",
  "dajaVehicles",
  "inglesFamily",
  "kiddoLearners",
  "kiddosBody",
  "kiddosFirstWords",
  "kiddosHundredWords",
  "missVBody",
  "msRachelSigns",
  "pagePeekabooWater",
  "rockNLearnHome",
  "tataaaOutside",
  "vlitActions",
  "yippeeWords",
] as const;

const VideoSourceKeySchema = z.enum(VIDEO_SOURCE_KEYS);

const VideoSourceSchema = z.object({
  youtubeVideoId: z.string().regex(YOUTUBE_VIDEO_ID_PATTERN),
  sourceTitle: z.string().min(1),
  sourceChannel: z.string().min(1),
});

const VIDEO_SOURCES = z.record(VideoSourceKeySchema, VideoSourceSchema).parse({
  abcFirstWords: {
    youtubeVideoId: "mazp6yogJ7g",
    sourceTitle:
      "100 First Words for Babies and Toddlers| Learn to Talk for Babies | Toddlers First Words",
    sourceChannel: "abc Learning Lane",
  },
  brightyVehicles: {
    youtubeVideoId: "LRAvLj5yHSw",
    sourceTitle:
      "120+ Vehicle Names | Learn Vehicle Names in English with sounds | Mode of Transport for kids",
    sourceChannel: "BrightyBees",
  },
  dajaVehicles: {
    youtubeVideoId: "7NmqKXdnf-g",
    sourceTitle:
      "Baby's First Words #12 - Learn Means of Transport Names and Sounds with Lucas | RV AppStudios Games",
    sourceChannel: "Daja Kids Games",
  },
  inglesFamily: {
    youtubeVideoId: "QrmTyWJy_0g",
    sourceTitle:
      "Super Teddy S3E2: Learn: Grandma, grandpa, mommy, daddy, uncle, aunt, brother and sister.",
    sourceChannel: "InglesKids",
  },
  kiddoLearners: {
    youtubeVideoId: "BW2A3e1dpLg",
    sourceTitle:
      "First 100 Words for Kids | Ms Rachel Style Animated Read Aloud for Babies & Toddlers | Learn To Talk",
    sourceChannel: "kiddo learners",
  },
  kiddosBody: {
    youtubeVideoId: "G-7AMnZLOCM",
    sourceTitle:
      "Body Parts for Kids | Learn Body Parts Hands, Eyes, Legs, Nose, Ears & More | Lucas & Friends",
    sourceChannel: "Toddler Learning Videos For Kids - Lucas & Friends",
  },
  kiddosFirstWords: {
    youtubeVideoId: "ZONJoCIaHlk",
    sourceTitle:
      "First Words for Babies - Teaching Toddlers to Talk - Learning Basic English Words",
    sourceChannel: "Kiddos World TV",
  },
  kiddosHundredWords: {
    youtubeVideoId: "gS5GuGE_kK8",
    sourceTitle: "First 100 Words for Children English Vocabulary Learning",
    sourceChannel: "Kiddos World TV",
  },
  missVBody: {
    youtubeVideoId: "hNMsO8Vxz9o",
    sourceTitle: "Learning the Parts of the Body for Children with Miss V",
    sourceChannel: "Kiddos World TV",
  },
  msRachelSigns: {
    youtubeVideoId: "glDJI7UKfbw",
    sourceTitle:
      "Baby Sign Language Basics and Baby First Words - The Best Baby Signs, Songs and Flashcards",
    sourceChannel: "Ms Rachel - Toddler Learning Videos",
  },
  pagePeekabooWater: {
    youtubeVideoId: "DWqR1r1lVo4",
    sourceTitle: "💧 Water | First Words for Kids | Cartoon Animation | PagePeekaboo",
    sourceChannel: "PagePeekaboo",
  },
  rockNLearnHome: {
    youtubeVideoId: "_J0nISRrVmY",
    sourceTitle: "Learn English | Objects in the Home | Rock ’N Learn",
    sourceChannel: "Rock 'N Learn",
  },
  tataaaOutside: {
    youtubeVideoId: "q4RWAtcqccY",
    sourceTitle:
      "Learn New Words | Vocabulary for Kids | Tree Leaf Flower Sun Moon | @Tataaarhymes Early Learning",
    sourceChannel: "Tataaa",
  },
  vlitActions: {
    youtubeVideoId: "_DiJsdGC2U8",
    sourceTitle:
      "100 Action Words (Verbs) in English | Learn Vocabulary with Sentences for Kids & Toddlers",
    sourceChannel: "Vlit Kids - Cartoons & Learning for Kids!",
  },
  yippeeWords: {
    youtubeVideoId: "87OZpL71F_s",
    sourceTitle:
      "100 Essential English Words for Kids | English Vocabulary for Kids | Video Flashcards for Kids",
    sourceChannel: "Yippee Kids",
  },
});

const VideoClipSpecSchema = z.object({
  source: VideoSourceKeySchema,
  startSeconds: z.int().min(0),
  note: z.string().min(1).optional(),
});

const VIDEO_CLIP_SPECS = z.record(AvaFirstWordSlugSchema, VideoClipSpecSchema).parse({
  mommy: { source: "inglesFamily", startSeconds: 164 },
  daddy: { source: "inglesFamily", startSeconds: 157 },
  baby: { source: "kiddosFirstWords", startSeconds: 337 },
  grandma: { source: "inglesFamily", startSeconds: 28 },
  grandpa: { source: "inglesFamily", startSeconds: 9 },
  brother: { source: "inglesFamily", startSeconds: 93 },
  sister: { source: "inglesFamily", startSeconds: 107 },
  friend: { source: "msRachelSigns", startSeconds: 1741 },
  boy: { source: "msRachelSigns", startSeconds: 776 },
  girl: { source: "msRachelSigns", startSeconds: 796 },
  dog: { source: "abcFirstWords", startSeconds: 100 },
  cat: { source: "abcFirstWords", startSeconds: 458 },
  bird: { source: "kiddosHundredWords", startSeconds: 1130 },
  fish: { source: "abcFirstWords", startSeconds: 285 },
  cow: { source: "abcFirstWords", startSeconds: 505 },
  horse: { source: "abcFirstWords", startSeconds: 827 },
  duck: { source: "abcFirstWords", startSeconds: 963 },
  bunny: { source: "abcFirstWords", startSeconds: 736, note: "Caption says rabbit." },
  bear: { source: "kiddosHundredWords", startSeconds: 645 },
  frog: { source: "abcFirstWords", startSeconds: 1112 },
  apple: { source: "abcFirstWords", startSeconds: 7 },
  banana: { source: "abcFirstWords", startSeconds: 123 },
  milk: { source: "abcFirstWords", startSeconds: 677 },
  water: { source: "pagePeekabooWater", startSeconds: 0 },
  bread: { source: "abcFirstWords", startSeconds: 861 },
  cheese: { source: "kiddosHundredWords", startSeconds: 89 },
  egg: { source: "abcFirstWords", startSeconds: 895 },
  cookie: { source: "abcFirstWords", startSeconds: 390 },
  juice: { source: "kiddosHundredWords", startSeconds: 801 },
  peas: { source: "abcFirstWords", startSeconds: 952 },
  eyes: { source: "kiddosBody", startSeconds: 59 },
  nose: { source: "kiddosBody", startSeconds: 141 },
  mouth: { source: "kiddosBody", startSeconds: 222 },
  ears: { source: "missVBody", startSeconds: 133 },
  hands: { source: "kiddosBody", startSeconds: 20 },
  feet: { source: "missVBody", startSeconds: 574 },
  hair: { source: "kiddosHundredWords", startSeconds: 770 },
  teeth: {
    source: "missVBody",
    startSeconds: 193,
    note: "The auto-caption garbles the answer; the visual lesson explicitly introduces teeth and tongue.",
  },
  belly: {
    source: "missVBody",
    startSeconds: 335,
    note: "Caption uses the plural bellies after the stomach segment.",
  },
  face: { source: "kiddoLearners", startSeconds: 326 },
  bed: { source: "rockNLearnHome", startSeconds: 142 },
  chair: { source: "rockNLearnHome", startSeconds: 33 },
  table: { source: "rockNLearnHome", startSeconds: 73 },
  door: { source: "rockNLearnHome", startSeconds: 81 },
  window: { source: "rockNLearnHome", startSeconds: 21 },
  light: { source: "rockNLearnHome", startSeconds: 106, note: "Caption and visual say lamp." },
  bath: { source: "abcFirstWords", startSeconds: 333 },
  book: { source: "abcFirstWords", startSeconds: 941 },
  blanket: { source: "rockNLearnHome", startSeconds: 118 },
  phone: { source: "abcFirstWords", startSeconds: 792, note: "Caption says telephone." },
  ball: { source: "abcFirstWords", startSeconds: 838 },
  blocks: { source: "yippeeWords", startSeconds: 566 },
  doll: { source: "abcFirstWords", startSeconds: 654 },
  "teddy-bear": { source: "abcFirstWords", startSeconds: 344 },
  car: { source: "kiddosHundredWords", startSeconds: 66 },
  train: { source: "kiddosHundredWords", startSeconds: 826 },
  bubbles: { source: "abcFirstWords", startSeconds: 528 },
  puzzle: { source: "abcFirstWords", startSeconds: 401 },
  crayon: { source: "abcFirstWords", startSeconds: 1089 },
  drum: { source: "kiddosHundredWords", startSeconds: 233, note: "Caption says drums." },
  sun: { source: "tataaaOutside", startSeconds: 53 },
  moon: { source: "tataaaOutside", startSeconds: 59 },
  star: { source: "tataaaOutside", startSeconds: 66 },
  tree: { source: "tataaaOutside", startSeconds: 4 },
  flower: { source: "tataaaOutside", startSeconds: 17 },
  grass: { source: "tataaaOutside", startSeconds: 23 },
  rain: { source: "tataaaOutside", startSeconds: 47 },
  cloud: { source: "tataaaOutside", startSeconds: 42 },
  rock: { source: "kiddosHundredWords", startSeconds: 751, note: "Caption says stones." },
  leaf: { source: "tataaaOutside", startSeconds: 11 },
  bus: { source: "brightyVehicles", startSeconds: 587 },
  truck: { source: "brightyVehicles", startSeconds: 732 },
  bicycle: { source: "brightyVehicles", startSeconds: 115 },
  airplane: { source: "brightyVehicles", startSeconds: 282 },
  boat: { source: "brightyVehicles", startSeconds: 833 },
  stroller: { source: "dajaVehicles", startSeconds: 105 },
  wagon: { source: "dajaVehicles", startSeconds: 125 },
  tractor: { source: "brightyVehicles", startSeconds: 370 },
  helicopter: { source: "brightyVehicles", startSeconds: 231 },
  scooter: { source: "brightyVehicles", startSeconds: 128 },
  eat: { source: "kiddoLearners", startSeconds: 465 },
  drink: { source: "kiddoLearners", startSeconds: 486 },
  sleep: { source: "kiddoLearners", startSeconds: 507 },
  sit: { source: "kiddoLearners", startSeconds: 549 },
  stand: { source: "kiddoLearners", startSeconds: 535 },
  walk: { source: "vlitActions", startSeconds: 1381 },
  run: { source: "vlitActions", startSeconds: 47 },
  jump: { source: "vlitActions", startSeconds: 30 },
  clap: { source: "vlitActions", startSeconds: 104 },
  hug: { source: "vlitActions", startSeconds: 1527 },
  more: { source: "msRachelSigns", startSeconds: 24 },
  "all-done": { source: "msRachelSigns", startSeconds: 55 },
  yes: { source: "kiddoLearners", startSeconds: 588 },
  no: { source: "kiddoLearners", startSeconds: 608 },
  please: { source: "kiddoLearners", startSeconds: 690 },
  "thank-you": { source: "kiddoLearners", startSeconds: 627 },
  help: { source: "kiddosFirstWords", startSeconds: 412 },
  up: { source: "vlitActions", startSeconds: 1457, note: "Caption says getting up." },
  down: { source: "kiddoLearners", startSeconds: 556, note: "Caption says sit down." },
  go: { source: "msRachelSigns", startSeconds: 1816 },
});

export const AVA_FIRST_WORD_VIDEO_CLIPS: AvaFirstWordVideoManifest =
  AvaFirstWordVideoManifestSchema.parse(
    Object.fromEntries(
      Object.entries(VIDEO_CLIP_SPECS).map(([slug, spec]) => {
        const source = VIDEO_SOURCES[spec.source];
        return [
          slug,
          {
            ...source,
            startSeconds: spec.startSeconds,
            durationSeconds: 5,
            ...(spec.note ? { note: spec.note } : {}),
          },
        ];
      }),
    ),
  );
