// @ts-nocheck
// This file is auto-generated by the @tanstack/react-router plugin on dev/build.
// The committed stub keeps `tsgo --noEmit` green on a fresh `bun install` before
// the plugin regenerates it. Do NOT hand-edit — the plugin will overwrite.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

export const routeTree = rootRouteImport._addFileChildren({ IndexRoute });
