/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsIndexRouteImport } from './routes/apps.index'
import { Route as GoalGoalIdRouteImport } from './routes/goal.$goalId'
import { Route as CurriculumCurriculumIdRouteImport } from './routes/curriculum.$curriculumId'
import { Route as AppsVectorDungeonRouteImport } from './routes/apps.vector-dungeon'
import { Route as CurriculumCurriculumIdIndexRouteImport } from './routes/curriculum.$curriculumId.index'
import { Route as CurriculumCurriculumIdStudyRouteImport } from './routes/curriculum.$curriculumId.study'
import { Route as AppsVectorDungeonPrintRouteImport } from './routes/apps.vector-dungeon_.print'
import { Route as CurriculumCurriculumIdNodeNodeIdRouteImport } from './routes/curriculum.$curriculumId.node.$nodeId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsRoute,
} as any)
const GoalGoalIdRoute = GoalGoalIdRouteImport.update({
  id: '/goal/$goalId',
  path: '/goal/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumCurriculumIdRoute = CurriculumCurriculumIdRouteImport.update({
  id: '/curriculum/$curriculumId',
  path: '/curriculum/$curriculumId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsVectorDungeonRoute = AppsVectorDungeonRouteImport.update({
  id: '/vector-dungeon',
  path: '/vector-dungeon',
  getParentRoute: () => AppsRoute,
} as any)
const CurriculumCurriculumIdIndexRoute =
  CurriculumCurriculumIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CurriculumCurriculumIdRoute,
  } as any)
const CurriculumCurriculumIdStudyRoute =
  CurriculumCurriculumIdStudyRouteImport.update({
    id: '/study',
    path: '/study',
    getParentRoute: () => CurriculumCurriculumIdRoute,
  } as any)
const AppsVectorDungeonPrintRoute = AppsVectorDungeonPrintRouteImport.update({
  id: '/vector-dungeon_/print',
  path: '/vector-dungeon/print',
  getParentRoute: () => AppsRoute,
} as any)
const CurriculumCurriculumIdNodeNodeIdRoute =
  CurriculumCurriculumIdNodeNodeIdRouteImport.update({
    id: '/node/$nodeId',
    path: '/node/$nodeId',
    getParentRoute: () => CurriculumCurriculumIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteWithChildren
  '/goals': typeof GoalsRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/apps/vector-dungeon': typeof AppsVectorDungeonRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRouteWithChildren
  '/goal/$goalId': typeof GoalGoalIdRoute
  '/apps/': typeof AppsIndexRoute
  '/apps/vector-dungeon/print': typeof AppsVectorDungeonPrintRoute
  '/curriculum/$curriculumId/study': typeof CurriculumCurriculumIdStudyRoute
  '/curriculum/$curriculumId/': typeof CurriculumCurriculumIdIndexRoute
  '/curriculum/$curriculumId/node/$nodeId': typeof CurriculumCurriculumIdNodeNodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goals': typeof GoalsRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/apps/vector-dungeon': typeof AppsVectorDungeonRoute
  '/goal/$goalId': typeof GoalGoalIdRoute
  '/apps': typeof AppsIndexRoute
  '/apps/vector-dungeon/print': typeof AppsVectorDungeonPrintRoute
  '/curriculum/$curriculumId/study': typeof CurriculumCurriculumIdStudyRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdIndexRoute
  '/curriculum/$curriculumId/node/$nodeId': typeof CurriculumCurriculumIdNodeNodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteWithChildren
  '/goals': typeof GoalsRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/apps/vector-dungeon': typeof AppsVectorDungeonRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRouteWithChildren
  '/goal/$goalId': typeof GoalGoalIdRoute
  '/apps/': typeof AppsIndexRoute
  '/apps/vector-dungeon_/print': typeof AppsVectorDungeonPrintRoute
  '/curriculum/$curriculumId/study': typeof CurriculumCurriculumIdStudyRoute
  '/curriculum/$curriculumId/': typeof CurriculumCurriculumIdIndexRoute
  '/curriculum/$curriculumId/node/$nodeId': typeof CurriculumCurriculumIdNodeNodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/goals'
    | '/progress'
    | '/settings'
    | '/apps/vector-dungeon'
    | '/curriculum/$curriculumId'
    | '/goal/$goalId'
    | '/apps/'
    | '/apps/vector-dungeon/print'
    | '/curriculum/$curriculumId/study'
    | '/curriculum/$curriculumId/'
    | '/curriculum/$curriculumId/node/$nodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/goals'
    | '/progress'
    | '/settings'
    | '/apps/vector-dungeon'
    | '/goal/$goalId'
    | '/apps'
    | '/apps/vector-dungeon/print'
    | '/curriculum/$curriculumId/study'
    | '/curriculum/$curriculumId'
    | '/curriculum/$curriculumId/node/$nodeId'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/goals'
    | '/progress'
    | '/settings'
    | '/apps/vector-dungeon'
    | '/curriculum/$curriculumId'
    | '/goal/$goalId'
    | '/apps/'
    | '/apps/vector-dungeon_/print'
    | '/curriculum/$curriculumId/study'
    | '/curriculum/$curriculumId/'
    | '/curriculum/$curriculumId/node/$nodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRouteWithChildren
  GoalsRoute: typeof GoalsRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  CurriculumCurriculumIdRoute: typeof CurriculumCurriculumIdRouteWithChildren
  GoalGoalIdRoute: typeof GoalGoalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof AppsRoute
    }
    '/goal/$goalId': {
      id: '/goal/$goalId'
      path: '/goal/$goalId'
      fullPath: '/goal/$goalId'
      preLoaderRoute: typeof GoalGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$curriculumId': {
      id: '/curriculum/$curriculumId'
      path: '/curriculum/$curriculumId'
      fullPath: '/curriculum/$curriculumId'
      preLoaderRoute: typeof CurriculumCurriculumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/vector-dungeon': {
      id: '/apps/vector-dungeon'
      path: '/vector-dungeon'
      fullPath: '/apps/vector-dungeon'
      preLoaderRoute: typeof AppsVectorDungeonRouteImport
      parentRoute: typeof AppsRoute
    }
    '/curriculum/$curriculumId/': {
      id: '/curriculum/$curriculumId/'
      path: '/'
      fullPath: '/curriculum/$curriculumId/'
      preLoaderRoute: typeof CurriculumCurriculumIdIndexRouteImport
      parentRoute: typeof CurriculumCurriculumIdRoute
    }
    '/curriculum/$curriculumId/study': {
      id: '/curriculum/$curriculumId/study'
      path: '/study'
      fullPath: '/curriculum/$curriculumId/study'
      preLoaderRoute: typeof CurriculumCurriculumIdStudyRouteImport
      parentRoute: typeof CurriculumCurriculumIdRoute
    }
    '/apps/vector-dungeon_/print': {
      id: '/apps/vector-dungeon_/print'
      path: '/vector-dungeon/print'
      fullPath: '/apps/vector-dungeon/print'
      preLoaderRoute: typeof AppsVectorDungeonPrintRouteImport
      parentRoute: typeof AppsRoute
    }
    '/curriculum/$curriculumId/node/$nodeId': {
      id: '/curriculum/$curriculumId/node/$nodeId'
      path: '/node/$nodeId'
      fullPath: '/curriculum/$curriculumId/node/$nodeId'
      preLoaderRoute: typeof CurriculumCurriculumIdNodeNodeIdRouteImport
      parentRoute: typeof CurriculumCurriculumIdRoute
    }
  }
}

interface AppsRouteChildren {
  AppsVectorDungeonRoute: typeof AppsVectorDungeonRoute
  AppsIndexRoute: typeof AppsIndexRoute
  AppsVectorDungeonPrintRoute: typeof AppsVectorDungeonPrintRoute
}

const AppsRouteChildren: AppsRouteChildren = {
  AppsVectorDungeonRoute: AppsVectorDungeonRoute,
  AppsIndexRoute: AppsIndexRoute,
  AppsVectorDungeonPrintRoute: AppsVectorDungeonPrintRoute,
}

const AppsRouteWithChildren = AppsRoute._addFileChildren(AppsRouteChildren)

interface CurriculumCurriculumIdRouteChildren {
  CurriculumCurriculumIdStudyRoute: typeof CurriculumCurriculumIdStudyRoute
  CurriculumCurriculumIdIndexRoute: typeof CurriculumCurriculumIdIndexRoute
  CurriculumCurriculumIdNodeNodeIdRoute: typeof CurriculumCurriculumIdNodeNodeIdRoute
}

const CurriculumCurriculumIdRouteChildren: CurriculumCurriculumIdRouteChildren =
  {
    CurriculumCurriculumIdStudyRoute: CurriculumCurriculumIdStudyRoute,
    CurriculumCurriculumIdIndexRoute: CurriculumCurriculumIdIndexRoute,
    CurriculumCurriculumIdNodeNodeIdRoute:
      CurriculumCurriculumIdNodeNodeIdRoute,
  }

const CurriculumCurriculumIdRouteWithChildren =
  CurriculumCurriculumIdRoute._addFileChildren(
    CurriculumCurriculumIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRouteWithChildren,
  GoalsRoute: GoalsRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  CurriculumCurriculumIdRoute: CurriculumCurriculumIdRouteWithChildren,
  GoalGoalIdRoute: GoalGoalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
