#!/usr/bin/env bash
# Fail if bun.lock references apps/test-project. That directory is
# generated by `turbo gen app` for /five-phase-pass and is gitignored,
# so any workspace entry leaks into CI as a frozen-lockfile failure.
# See commit 10c6298 for the original incident.
set -euo pipefail

if grep -q 'apps/test-project' bun.lock; then
  echo "error: bun.lock references apps/test-project (gitignored)." >&2
  echo "Run: mv apps/test-project /tmp/stash && bun install && mv /tmp/stash apps/test-project" >&2
  exit 1
fi
